#!/usr/bin/python3

import sys
import os
from math import sqrt

if len(sys.argv) != 2:
    print('Usage: factors <file>')
    sys.exit(1)

os.chdir(os.path.dirname(os.path.abspath(__file__)))
file =  open(sys.argv[1], "r")

number = 0
q = 2
n = 0
for line in file:
    number = int(line)
    n = int(sqrt(number)) + 1
    for p in range(2, n):
        if number % p == 0:
            q = number // p
            print(f"{number}={q}*{p}")
            break
        elif number % n == 0:
            q = number // n
            print(f"{number}={q}*{n}")
            break
        n -= 1
file.close()
